### ISSUE TITLE
Adjustable timer when an option is selected

### ISSUE THREAD

**Issue by domudev** [domudev/wheelpick#1]
- The timer should start as soon as an option is selected
- the Timer should be adjustable (e.g. 1 min per option)
- There should be an option to automatically spin the wheel after the time is over

**Comment by fallshare** [comment]
It would also be nice to have the following features:

- there should be an option to pause and resume the timer
- there should be an option to reset the timer


Regarding "The timer should start as soon as an option is selected" maybe this could also be optional. On the other hand one can manually stop the timer after an option was selected.
